### ISSUE TITLE
Doesn't work with Facebook Open Graph?

### ISSUE THREAD

**Issue by alesthome** [mcasimir/meta-tags-helpers#2]
Open Graph seems to require the tag to be defined by "property" as opposed to "name".

**Comment by mcasimir** [comment]
You're right.. also considering the occurrence of other attributes such as `http-equiv` it could be a good idea to switch to  something better than a simple helper method to modify an hash.

I'll probably end up with something like:

``` rhtml

<%= meta_tags do
    meta           "title",        "MyBlog - This is a Blog"
    meta           "description",  "The blog of mine & a reserved character"
    http_equiv     "content-type", "text/html; charset=UTF-8"
    property       "og:type",      "website"
    meta           "My Key",       "My Value", key_attr: "key", value_attr: "value"
    # => <meta key="My Key" value="My Value" />
   end 
%>

```

This way should be even simpler to express conditional meta tags:

``` rb
if home?
   property "og:type", "website"
else
   property "og:type", "article"
end

```

**Comment by mcasimir** [comment]
Ok in the meanwhile i fixed it estabilishing that any namespaced meta imply an RDFa property so:
og:title and ns:myprop are rendered with the `property` attribute.

Thank you for reporting this issue!

**Comment by alesthome** [comment]
Works great. Thanks!!
